### ISSUE TITLE
Zippyshare changed algo

### ISSUE THREAD

**Issue by miguelvillanma** [stck-lzm/badown#4]
Hi,
It seems like Zippy changed something internally and your approach is not working anymore.

Found this https://github.com/ffluegel/zippyshare/blob/master/zippyshare.sh, and it's updated to this new algorithm. Maybe you can fork it somehow.

Thank you

**Comment by stck-lzm** [comment]
Hello,

I have quickly look at your link and it appear they do adapt the algo with zippy update, which is what is happening with badown atm (with a lot of delay :/).
If I have to fix this once again I would like to implement something more stable, more permanent.
Since everything is just simple mathematical operation over couple of line there is 2 path of reflexion:
- bash can sort things out in the same format as js, so one need to parse js into bash.
- bash cannot do the math itself and need some kind of interpreter then I ll start looking into small/compact interpreter that can be called by bash.

If you have more information, please share :)
lzm

**Comment by stck-lzm** [comment]
ok, fixed, here 5728d4c
but its just temporary fix :/
